users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
from .views import RegisterUser

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from core.models import Doctor


class User(AbstractUser):
    phone_number = models.CharField(blank=True, default=0, max_length=12)
    doctor = models.OneToOneField(to=Doctor, on_delete=models.PROTECT, default=None, null=True)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин или E-mail', widget=forms.TextInput(attrs={'class': "form-control"}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': "form-control"}))

    class Meta:
        model = get_user_model()


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': "form-control"}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': "form-control"}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': "form-control"}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': "form-control"}),
            'first_name': forms.TextInput(attrs={'class': "form-control"}),
            'last_name': forms.TextInput(attrs={'class': "form-control"})
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        user = get_user_model().objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError('Пользователь с таким E-mail уже существует!')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(disabled=True, required=False, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib import messages

from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    """
    View for user login.

    Presents a form for user login.
    """
    form_class = LoginUserForm
    template_name = 'new/login.html'
    extra_context = {'title': 'Вход в в профиль пользователя'}


class RegisterUser(CreateView):
    """
    View for registering a new user.

    Presents a form for registering a new user. On successful registration, redirects
    to the login page.

    Attributes:
        form_class (Form): The form class for user registration.
        template_name (str): The name of the template to render.
        extra_context (dict): Extra context data to pass to the template.
        success_url (str): The URL to redirect to after successful registration.
    """
    form_class = RegisterUserForm
    template_name = 'new/register.html'
    extra_context = {'title': 'Регистрация  пользователя'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    """
    View for updating user profile information.

    Presents a form for updating user profile information. Only accessible to logged-in users.
    """
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Ваши данные были успешно обновлены!')
        return super().form_valid(form)


class UserPasswordChange(PasswordChangeView):
    """
    View for changing user password.

    Presents a form for changing the user password.
    """
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6">
            <!-- The form begins here -->
            <form method="post" class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <img src="https://img.freepik.com/free-vector/two-factor-authentication-concept-illustration_114360-5280.jpg?w=1060&t=st=1708528935~exp=1708529535~hmac=ed18936ad7898ec9142cc158e2cca393a63b681b8d7a91f7bc1b64367fc16c65"
                     class="img-fluid mb-4" style="max-width: 200px;">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <!-- Display the form fields here -->
                <div class="text-danger">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label>{{ f }}</p>
                <div class="text-danger">{{ f.errors }}</div>
                {% endfor %}
                <button class="btn btn-outline-dark" type="submit"><i class="fas fa-door-open me-2"></i>Войти</button>
                <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
            </form>

            <div class="row justify-content-center">
</div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<div class="container py-4">
          <div class="row gy-5">
            <div class="col-lg-9 order-2 order-lg-1">
              <p class="lead mb-4">Вы можете сменить свои данные на этой странице</p>
              <!-- PROFILE DETAIL FORM-->
              <h3 class="text-uppercase lined">Детали профиля</h3>
            <div class="col-lg-6 mx-auto">
            <h1>Пароль успешно изменен!</h1>

            <p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
                </div>
            </div>
            <div class="col-lg-3 order-1 order-lg-2">
              <h3 class="h4 text-uppercase lined mb-4">Ваш профиль</h3>
              <nav class="nav flex-column nav-pills">
                  <a class="nav-link text-sm" href="{% url 'users:profile' %}"> <i class="me-2 fas fa-user"></i><span>Мой профиль</span></a>
                  <a class="nav-link text-sm active" href="{% url 'users:password_change' %}"> <i class="me-2 fas fa-pen"></i><span>Смена пароля</span></a>
                  <a class="nav-link text-sm" href="#"> <i class="me-2 fas fa-list"></i><span>История заказов</span></a>
                  <a class="nav-link text-sm" href="#"> <i class="me-2 fas fa-heart"></i><span>Список желаний</span></a>
                  <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                            {% csrf_token %}
                            </form>
                  <a class="nav-link text-sm" href="{% url 'users:logout' %}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> <i class="me-2 fas fa-door-open"></i><span>Выход</span></a>
              </nav>
            </div>
          </div>
        </div>

{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}
 
{% block content %}
<section class="py-1 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Смена пароля</h1>
              </div>
              <div class="col-lg-6 text-lg-end">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                    <li class="breadcrumb-item"><a class="text-dark" href="{% url 'home' %}">Главная</a></li>
                    <li class="breadcrumb-item"><a class="text-dark" href="{% url 'users:profile' %}">Мой профиль</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Смена пароля</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
<div class="container py-4">
          <div class="row gy-5">
            <div class="col-lg-9 order-2 order-lg-1">
              <p class="lead mb-4">Вы можете сменить пароль на этой странице</p>
              <!-- PROFILE DETAIL FORM-->
              <h3 class="text-uppercase lined">Смена пароля</h3>
            <div class="col-lg-6 mx-auto">
            <form method="post" class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <div class="col-lg-12 text-center">
                    <button class="btn btn-outline-dark" type="submit"> <i class="fas fa-save me-2"></i>Сохранить изменеия</button>
                  </div>
            </form>
                </div>
            </div>
            <div class="col-lg-3 order-1 order-lg-2">
              <h3 class="h4 text-uppercase lined mb-4">Ваш профиль</h3>
              <nav class="nav flex-column nav-pills">
                  <a class="nav-link text-sm" href="{% url 'users:profile' %}"> <i class="me-2 fas fa-user"></i><span>Мой профиль</span></a>
                  <a class="nav-link text-sm active" href="{% url 'users:password_change' %}"> <i class="me-2 fas fa-pen"></i><span>Смена пароля</span></a>
                  <a class="nav-link text-sm" href="{% url 'orders:orders_history' %}"> <i class="me-2 fas fa-list"></i><span>История заказов</span></a>
                  <a class="nav-link text-sm" href="{% url 'preorders:preorders_history' %}"> <i class="me-2 fas fa-heart"></i><span>История предзаказов</span></a>
                  <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                            {% csrf_token %}
                            </form>
                  <a class="nav-link text-sm" href="{% url 'users:logout' %}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> <i class="me-2 fas fa-door-open"></i><span>Выход</span></a>
              </nav>
            </div>
          </div>
        </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
 
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Новый пароль</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>
 
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
 
{% block content %}
<h1>Сброс пароля</h1>
<p >{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Восстановление пароля</h1>
 
<form method="post">
    {% csrf_token %}
{% for f in form %}
<p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}
 
    <p ><button type="submit">Сбросить по E-mail</button></p>
</form>
 
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
 
{% block content %}
<section class="py-1 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Профиль пользователя</h1>
              </div>
              <div class="col-lg-6 text-lg-end">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                    <li class="breadcrumb-item"><a class="text-dark" href="{% url 'home' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Мой профиль</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
<div class="container py-4">
          <div class="row gy-5">
            <div class="col-lg-9 order-2 order-lg-1">
              <!-- PROFILE DETAIL FORM-->
            <div class="col-lg-6 mx-auto">
            <form method="post" class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <div class="col-lg-12 text-center">
                    <button class="btn btn-outline-dark" type="submit"> <i class="fas fa-save me-2"></i>Сохранить изменеия</button>
                  </div>
            </form>
                </div>
            </div>
            <div class="col-lg-3 order-1 order-lg-2">
              <h3 class="h4 text-uppercase lined mb-4">Ваш профиль</h3>
              <nav class="nav flex-column nav-pills">
                  <a class="nav-link text-sm active" href="{% url 'users:profile' %}"> <i class="me-2 fas fa-user"></i><span>Мой профиль</span></a>
                  {% if not perms.users.social_auth %}
                  <a class="nav-link text-sm" href="{% url 'users:password_change' %}"> <i class="me-2 fas fa-pen"></i><span>Смена пароля</span></a>
                  {% endif %}
                  <a class="nav-link text-sm" href="{% url 'orders:orders_history' %}"> <i class="me-2 fas fa-list"></i><span>История заказов</span></a>
                  <a class="nav-link text-sm" href="{% url 'preorders:preorders_history' %}"> <i class="me-2 fas fa-heart"></i><span>История предзаказов</span></a>
                  <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                            {% csrf_token %}
                            </form>
                  <a class="nav-link text-sm" href="{% url 'users:logout' %}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> <i class="me-2 fas fa-door-open"></i><span>Выход</span></a>
              </nav>
            </div>
          </div>
        </div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6">
            <!-- The form begins here -->
            <form method="post" class="text-center">
                <img src="https://img.freepik.com/free-vector/two-factor-authentication-concept-illustration_114360-5280.jpg?w=1060&t=st=1708528935~exp=1708529535~hmac=ed18936ad7898ec9142cc158e2cca393a63b681b8d7a91f7bc1b64367fc16c65"
                     class="img-fluid mb-4" style="max-width: 200px;">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <!-- Display the form fields here -->
                <div class="text-danger">{{ form.non_field_errors }}</div>
                <h4>Регистрация:</h4>
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label>{{ f }}</p>
                <div class="text-danger">{{ f.errors }}</div>
                {% endfor %}
                <button class="btn btn-outline-dark" type="submit"><i class="fas fa-door-open me-2"></i>Зарегестрироваться</button>
            </form>
            <!-- The form ends here -->
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6">
            <!-- The form begins here -->
            <div class="text-center">
                <img src="https://img.freepik.com/free-vector/two-factor-authentication-concept-illustration_114360-5280.jpg?w=1060&t=st=1708528935~exp=1708529535~hmac=ed18936ad7898ec9142cc158e2cca393a63b681b8d7a91f7bc1b64367fc16c65"
                     class="img-fluid mb-4" style="max-width: 200px;">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <a href="{% url 'users:login' %}">
                    <button class="btn btn-outline-primary" type="submit"><i class="fas fa-door-open me-2"></i>Войти</button>
                </a>
            </div>

            <!-- The form ends here -->
        </div>
    </div>
</div>
{% endblock %}