annamedical/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from annamedical import settings
from core.views import custom_page_not_found_view

handler404 = custom_page_not_found_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('core.urls', namespace='core')),
    path('appointments/', include('appointment.urls', namespace='appointment')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import PatientsAPIList, AppointmentsAPIList, AppointmentAPIView, PatientUpdate, CreatePatientAPIView, \
    CreateAppointmentAPIView, CreateServiceAPIView, AppointmentAPIUpdate, AddedAppointmentPhotoAPI, UpdateItemAPIView

app_name = 'api'

urlpatterns = [
    path('patients_list/', PatientsAPIList.as_view(), name='patients_list'),
    path('patient/<int:pk>/update/', PatientUpdate.as_view(), name='patient_update'),
    path('appointments/', AppointmentsAPIList.as_view(), name='all_appointments'),
    path('appointment/<int:pk>', AppointmentAPIView.as_view(), name='appointment_view'),
    path('create_patient/', CreatePatientAPIView.as_view(), name='create_patient'),
    path('create_appointment/', CreateAppointmentAPIView.as_view(), name='create_appointment'),
    path('create_service/', CreateServiceAPIView.as_view(), name='create_service'),
    path('appointment/<int:pk>/update/', AppointmentAPIUpdate.as_view(), name='appointment_update'),
    path('appointment/adding_photo/', AddedAppointmentPhotoAPI.as_view(), name='adding_appointment_photo'),
    path('appointment_item/<int:pk>/update/', UpdateItemAPIView.as_view(), name='appointment_item_update'),
]

appointment/urls.py
from django.urls import path
from . import views
from .views import UpdateAppointmentItemsView

app_name = 'appointment'

urlpatterns = [
    path('create_appointment/', views.CreateAppointmentVew.as_view(), name='create_appointment'),
    path('appointment_detail/<int:pk>/', views.AppointmentDitail.as_view(), name='appointment_detail'),
    path('appointments/<int:pk>/update-items/', UpdateAppointmentItemsView.as_view(), name='update_appointment_items'),
    # path('appointment_update/<int:pk>/', views.AppointmentUpdateView.as_view(), name='appointment_update'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('patients/', views.PatientsPage.as_view(), name='patients'),
    path('patient_detail/<int:pk>/', views.PatientDetail.as_view(), name='patient_detail'),
    path('user_profile/<int:pk>/', views.UserProfileView.as_view(), name='user_profile'),
    path('add_patient/', views.AddPatientView.as_view(), name='add_patient'),
    path('services/', views.ServicesView.as_view(), name='services'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
from .views import RegisterUser

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

appointment/models.py
from django.db import models

from annamedical import settings
from core.models import Patient, Doctor, Service, Clinic


class AppointmentStatus(models.TextChoices):
    PLANNED = 'planned', 'Запланировано'
    APPROVED = 'approved', 'Подтверждено'
    COMPLETED = 'completed', 'Завершено'
    CANCELED = 'canceled', 'Отменено'


class AppointmentType(models.TextChoices):
    PRIMARY = 'primary', 'Первичная'
    SECONDARY = 'secondary', 'Вторичная'


class Appointment(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    patient = models.ForeignKey(Patient, on_delete=models.PROTECT, related_name='appointments')
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT, related_name='appointments')
    type = models.CharField(max_length=100, choices=AppointmentType.choices)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=50, choices=AppointmentStatus.choices)
    clinic = models.ForeignKey(Clinic, on_delete=models.PROTECT, related_name='appointments')

    class Meta:
        ordering = ['start']


class AppointmentItem(models.Model):
    appointment = models.ForeignKey(Appointment, related_name='items', on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField(default=0)

    class Meta():
        ordering = ('service__name',)


class Media(models.Model):
    photo = models.ImageField(upload_to='appointments_media/', blank=True, null=True)
    video = models.FileField(upload_to='appointments_media/', blank=True, null=True)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='media')

    def __str__(self):
        if self.photo:
            return f"Photo {self.id}"
        elif self.video:
            return f"Video {self.id}"
        return f"Media {self.id}"

templates/new/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AnnaCareDent</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Updated: Apr 20 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'core:index' %}" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span class="d-none d-lg-block">AnnaCareDent</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->


    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            {% if appointments_missing %}
            <li class="nav-item dropdown">
                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-exclamation-circle" style="color:red"></i>
                    <span class="badge bg-primary badge-number">{{ appointments_missing|length }}</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        Не завершенные посещения: {{ appointments_missing|length }}
                    </li>
                    {% for appointment in appointments_missing %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <a href="{% url 'appointment:appointment_detail' appointment.pk %}">
                            <div>
                                <h4>{{ appointment.patient }}</h4>
                                <p>{{ appointment.start.date|date:"d/M" }} {{ appointment.start.time|time:"H:i" }}-{{ appointment.end.time|time:"H:i" }}</p>
                            </div>
                        </a>
                    </li>

                    {% endfor %}

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->
            {% endif %}
            {% if appointments_by_doctor_today %}
            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">{{ appointments_by_doctor_today|length }}</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        Ваши записи на сегодня: {{ appointments_by_doctor_today|length }}
                    </li>
                    {% for appointment in appointments_by_doctor_today %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-bookmark-check" style="color:green;"></i>
                        <a href="{% url 'appointment:appointment_detail' appointment.pk %}">
                            <div>
                                <h4>{{ appointment.patient }}</h4>
                                <p>{% for item in appointment.items.all %} {{ item.service }} {% if not forloop.last %}|{% endif %} {% endfor %}</p>
                                <p>{{ appointment.start.time|time:"H:i" }}-{{ appointment.end.time|time:"H:i" }}</p>
                            </div>
                        </a>
                    </li>

                    {% endfor %}

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="{{ user.doctor.photo.url }}" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.doctor.full_name }}</span>
                </a><!-- End Profile Iamge Icon -->
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ user.doctor.full_name }}</h6>
                        <span>{{ user.doctor.specialization }}</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'core:user_profile' request.user.id %}">
                            <i class="bi bi-person"></i>
                            <span>Мой профиль</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'users:logout' %}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Выйти</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->
            {% endif %}

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link {% if request.path != '/' %} collapsed {% endif %}" href="{% url 'core:index' %}">
                <i class="bi bi-journal-text"></i>
                <span>Ежедневник </span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link {% if request.path != '/patients/' %} collapsed {% endif %}" href="{% url 'core:patients' %}">
                <i class="bi bi-people"></i>
                <span>Пациенты</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link {% if request.path|slice:':14' != '/user_profile/' %} collapsed {% endif %}" href="{% url 'core:user_profile' request.user.id %}">
                <i class="bi bi-person"></i>
                <span>Профиль доктора</span>
            </a>
        </li><!-- End Profile Page Nav -->
        <li class="nav-item">
            <a class="nav-link {% if request.path|slice:':14' != '/services/' %} collapsed {% endif %}" href="{% url 'core:services' %}">
                <i class="ri-service-line"></i>
                <span>Услуги клиники</span>
            </a>
        </li>

    </ul>

</aside><!-- End Sidebar-->

{% block content %}
{% endblock %}

<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; <strong><span>AnnaCareDent</span></strong>
    </div>

</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->

<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/new/error-404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Not Found 404 - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section error-404 min-vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1>404</h1>
        <h2>Страница не существует.</h2>
        <a class="btn" href="{% url 'core:index' %}">На главную</a>
        <img src="{% static 'assets/img/not-found.svg' %}" class="img-fluid py-5" alt="Page Not Found">
      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/new/index.html
{% extends 'new/base.html' %}
{% load tz %}
{% block content %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Ежедневник</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">Ежедневник</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-8 order-2 order-lg-1">
                <div class="row">

                    <!-- Recent Sales -->
                    <div class="col-12">
                        <div class="card recent-sales overflow-auto">
                            <div class="card-body">
                                <h5 class="card-title">Записи пациентов <span>| Неделя</span></h5>

                                <table class="table table-borderless datatable">
                                    <thead>
                                    <tr>
                                        <th scope="col">Дата</th>
                                        <th scope="col">Время</th>
                                        <th scope="col">Пациент</th>
                                        <th scope="col">Клиника</th>
                                        <th scope="col">Процедура</th>
                                        <th scope="col">Доктор</th>
                                        <th scope="col">Статус</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for appointment in appointments %}
                                    <tr>
                                        <th scope="row">{{appointment.start.date|date:"D d-m"}}</th>
                                        <td>{{ appointment.start|timezone:"Europe/Moscow"|time:"H:i" }}-{{ appointment.end|timezone:"Europe/Moscow"|time:"H:i" }}</td>
                                        <td><a href="{% url 'core:patient_detail' appointment.patient.pk %}">{{ appointment.patient }}</a></td>
                                        <th scope="row">{{appointment.clinic}}</th>
                                        <td><a href="{% url 'appointment:appointment_detail' appointment.pk %}" class="text-primary">{% for item in appointment.items.all %} {{ item.service }} {% if not forloop.last %}<br>{% endif %} {% endfor %}</a></td>
                                        <th scope="row">{{appointment.doctor}}</th>
                                        <td><span class="badge bg-{% if appointment.status == 'approved' %}info
                                                                {% elif appointment.status == 'completed' %}success
                                                                {% elif appointment.status == 'planned' %}primary
                                                                {% elif appointment.status == 'canceled' %}danger
                                                                {% endif %}">{{appointment.get_status_display}}</span>
                                        {% if appointment.media.all %}
                                        <span><strong><i class="bi bi-camera"></i><i class="bi bi-check-circle-fill" style="color:green;"></i></strong></span>
                                        {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div><!-- End Recent Sales -->


                </div>
            </div><!-- End Left side columns -->

            <!-- Right side columns -->
            <div class="col-lg-4 col-12 order-1 order-lg-2">

                <!-- Recent Activity -->
                <div class="card">

                    <div class="card-body">
                        <h5 class="card-title">Фильтр посещений</h5>

                        <div class="activity">
                            <nav class="nav flex-column nav-pills">
                                <form id="patientFilterForm" action="{% url 'core:index' %}">
                                    <select class="form-select form-select-sm mb-1" aria-label="Large select example"
                                            id="doctor_id" name="doctor_id">
                                        <option {% if doctor_selected %}{%else%}selected{% endif %}>Доктор</option>
                                        {% for doctor in doctors %}
                                        <option value="{{ doctor.id }}" {% if doctor_selected == doctor %}selected{% endif %}>{{ doctor.full_name }}</option>
                                        {% endfor %}
                                    </select>
                                    <select class="form-select form-select-sm mb-1" aria-label="Small select example"
                                            id="clinic_id" name="clinic_id">
                                        <option {% if clinic_selected %}{%else%}selected{% endif %}>Клиника</option>
                                        {% for clinic in clinics %}
                                        <option value="{{ clinic.id }}" {% if clinic_selected == clinic %}selected{% endif %}>{{ clinic.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="start_date">С:</label>
                                                <input type="date" id="start_date" name="start_date" class="form-control" value="{% if start_date %}{{start_date}}{% endif %}">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="end_date">По:</label>
                                                <input type="date" id="end_date" name="end_date" class="form-control" value="{% if end_date %}{{end_date}}{% endif %}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-3 text-center">
                                        <button type="submit" class="btn btn-primary">Применить фильтр</button>
                                    </div>
                                </form>
                            </nav>
                        </div>
                    </div>
                </div><!-- End Recent Activity -->

            </div><!-- End Right side columns -->

        </div>
    </section>

</main><!-- End #main -->
<script>
    document.addEventListener("DOMContentLoaded", function() {
    var form = document.getElementById("patientFilterForm");
    var submitButton = form.querySelector("button[type='submit']");
    var originalFormData = new FormData(form);

    // Функция для проверки изменений в форме и активации кнопки
    function checkFormChanges() {
        var currentFormData = new FormData(form);
        var changed = false;

        // Сравниваем значения текущей формы с изначальными
        for (var pair of currentFormData.entries()) {
            if (pair[1] !== originalFormData.get(pair[0])) {
                changed = true;
                break;
            }
        }

        // Активируем кнопку, если есть изменения, иначе деактивируем
        submitButton.disabled = !changed;
    }

    // Добавляем обработчик событий на изменения в форме
    form.addEventListener("change", checkFormChanges);

    // Добавляем обработчик событий на ввод в текстовые поля формы
    var inputs = form.querySelectorAll("input[type='text'], input[type='number'], input[type='date']");
    inputs.forEach(function(input) {
        input.addEventListener("input", checkFormChanges);
    });

    // Обработчик отправки формы
    form.addEventListener("submit", function(event) {
        event.preventDefault(); // Предотвращаем отправку формы по умолчанию

        // Получаем значения выбранных параметров
        var doctorId = document.getElementById("doctor_id").value;
        var clinicId = document.getElementById("clinic_id").value;
        var startDate = document.getElementById("start_date").value;
        var endDate = document.getElementById("end_date").value;

        // Формируем URL с параметрами фильтрации
        var url = "{% url 'core:index' %}?";
        if (doctorId && doctorId !== 'Доктор') {
            url += "doctor_id=" + doctorId + "&";
        }
        if (clinicId && clinicId !== 'Клиника') {
            url += "clinic_id=" + clinicId + "&";
        }
        if (startDate) {
            url += "start_date=" + startDate + "&";
        }
        if (endDate) {
            url += "end_date=" + endDate + "&";
        }

        // Перенаправляем на новый URL
        window.location.href = url;
    });

    // Инициализируем состояние кнопки при загрузке страницы
    checkFormChanges();
});
</script>
{% endblock %}